import { DM_Serif_Text, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar";

const oswald = Poppins({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-Oswald",
	weight: ["400", "500", "600", "700"],
});
const DMserif = DM_Serif_Text({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-DMserif",
	weight: ["400"],
});

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased ${oswald.variable} ${DMserif.variable}`}
			>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
