// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
// const geistSans = Geist({
// 	variable: "--font-geist-sans",
// 	subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// import { Poppins } from "next/font/google";

// const oswald = Poppins({
// 	subsets: ["latin"],
// 	display: "swap",
// 	variable: "--font-Oswald",
// 	weight: ["400", "500", "600", "700"],
// });

export default function RootLayout({ children }) {
	return (
		<html>
			<Head>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
				/>
			</Head>
			<body>{children}</body>
		</html>
	);
}
